#!/bin/bash
# install-hooks.sh — wire the committed git hooks into this clone's .git/hooks.
#
# Git hooks live in .git/hooks/ which NEVER travels with clone/push — so every
# session/machine must run this ONCE to activate the repo's hooks.
#
#   bash scripts/install-hooks.sh
#
# Idempotent: safe to re-run. Re-points .git/hooks/post-commit at the committed
# scripts/hooks/post-commit.sh (the SCRATCHPAD commit logger).

set -euo pipefail

docs_dir="${TRACKER_DOCS_DIR:-Devins_Plans}"

REPO_ROOT="$(git rev-parse --show-toplevel)"
SRC="$REPO_ROOT/scripts/hooks/post-commit.sh"
DEST="$REPO_ROOT/.git/hooks/post-commit"

[ -f "$SRC" ] || { echo "✗ missing $SRC"; exit 1; }

# A thin shim so the active hook always runs the latest committed script.
cat > "$DEST" <<SHIM
#!/bin/bash
# Auto-generated by scripts/install-hooks.sh — runs the committed hook.
exec "$SRC" "\$@"
SHIM
chmod +x "$DEST" "$SRC"

echo "✓ post-commit hook installed → logs commits to $docs_dir/SCRATCHPAD.md"
echo "  (re-run anytime; coordination log now travels with the repo)"
